version: "3.4"
services:

  redis:
    image: redis
    hostname: redis
    networks:
      - hpndev
    ports:
      - 6379:6379

  exec:
    image: node
    volumes:
      - "./:/home"
    working_dir: "/home"
    command: [ "bash", "-c", "${FILE}" ]
    depends_on:
      - redis
    networks:
      - hpndev

  tests:
    image: node
    volumes:
      - "./:/home"
    working_dir: "/home"
    command: [ "node", "./tests/unit" ]
    depends_on:
      - redis
    networks:
      - hpndev

networks:
  hpndev:


